# Generated by Django 4.0.4 on 2022-04-15 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upswebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=128, unique=True)),
                ('truck_package_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=128, unique=True)),
                ('tracking_id', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('delivered', 'delivered'), ('delivering', 'delivering'), ('pick_up', 'pick_up'), ('loading', 'loading')], default='pick_up', max_length=32)),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upswebsite.truck')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upswebsite.user')),
            ],
        ),
    ]
