# Generated by Django 4.0.4 on 2022-04-16 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upswebsite', '0004_alter_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='dest',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('loading', 'loading'), ('delivering', 'delivering'), ('pick_up', 'pick_up')], default='pick_up', max_length=32),
        ),
        migrations.AlterField(
            model_name='package',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upswebsite.truck'),
        ),
        migrations.AlterField(
            model_name='package',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upswebsite.user'),
        ),
    ]
